# Generated by Django 5.2.17 on 2026-10-02 00:43

import django.db.models.deletion
import django.utils.timezone
import ecoles.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Classroom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Ex. : CM2 A, 6e B, Tle D",
                        max_length=50,
                        verbose_name="classe",
                    ),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="ordre d'affichage"
                    ),
                ),
            ],
            options={
                "verbose_name": "classe",
                "ordering": ["position", "name"],
            },
        ),
        migrations.CreateModel(
            name="FeeSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Ex. : Primaire, Collège, 3e/Tle",
                        max_length=80,
                        verbose_name="nom du barème",
                    ),
                ),
            ],
            options={
                "verbose_name": "barème",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, verbose_name="nom de l'établissement"
                    ),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="identifiant")),
                (
                    "country",
                    models.CharField(
                        choices=[
                            ("CI", "Côte d'Ivoire"),
                            ("SN", "Sénégal"),
                            ("CM", "Cameroun"),
                            ("BJ", "Bénin"),
                            ("TG", "Togo"),
                            ("BF", "Burkina Faso"),
                            ("ML", "Mali"),
                            ("NE", "Niger"),
                            ("GN", "Guinée"),
                            ("CG", "Congo-Brazzaville"),
                            ("CD", "RD Congo"),
                            ("MG", "Madagascar"),
                        ],
                        default="CI",
                        max_length=2,
                        verbose_name="pays",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("XOF", "XOF (FCFA)"),
                            ("XAF", "XAF (FCFA)"),
                            ("GNF", "GNF (GNF)"),
                            ("CDF", "CDF (FC)"),
                            ("MGA", "MGA (Ar)"),
                            ("USD", "USD (USD)"),
                        ],
                        default="XOF",
                        max_length=3,
                        verbose_name="monnaie",
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=80, verbose_name="ville"),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="adresse"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="téléphone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="e-mail"
                    ),
                ),
                (
                    "payment_instructions",
                    models.TextField(
                        blank=True,
                        help_text="Affiché aux parents. Ex. : Wave 07 00 00 00 00 — Orange Money 07 00 00 00 01 (indiquez le nom et la classe de l'élève en motif).",
                        verbose_name="comment payer",
                    ),
                ),
                (
                    "reminder_template",
                    models.TextField(
                        default="Bonjour {parent}, sauf erreur de notre part, un montant de {montant} reste à régler pour la scolarité de {eleve} ({classe}), échéance du {echeance}. Détail et paiement : {lien} . Merci pour votre confiance. — {ecole}",
                        help_text="Variables : {parent} {eleve} {classe} {montant} {echeance} {ecole} {lien}",
                        verbose_name="message de relance",
                    ),
                ),
                (
                    "receipt_footer",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="mention en bas des reçus",
                    ),
                ),
                (
                    "online_payment_provider",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "",
                                "Désactivé (paiement direct sur vos numéros marchands)",
                            ),
                            ("demo", "Démonstration (aucun argent réel)"),
                            ("cinetpay", "CinetPay (Orange, MTN, Moov, Wave…)"),
                        ],
                        max_length=20,
                        verbose_name="paiement en ligne",
                    ),
                ),
                (
                    "cinetpay_api_key",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="CinetPay — apikey"
                    ),
                ),
                (
                    "cinetpay_site_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="CinetPay — site_id"
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("essentiel", "Essentiel"),
                            ("recouvrement", "Recouvrement+"),
                        ],
                        default="essentiel",
                        max_length=20,
                        verbose_name="formule",
                    ),
                ),
                (
                    "price_per_student",
                    models.PositiveIntegerField(
                        default=500, verbose_name="prix par élève et par an"
                    ),
                ),
                (
                    "subscription_until",
                    models.DateField(
                        blank=True, null=True, verbose_name="abonnement payé jusqu'au"
                    ),
                ),
                (
                    "is_demo",
                    models.BooleanField(
                        default=False, verbose_name="école de démonstration"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "receipt_counter",
                    models.PositiveIntegerField(default=0, editable=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "école",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discount",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Bourse, réduction fratrie… déduite des dernières échéances.",
                        verbose_name="remise",
                    ),
                ),
                (
                    "discount_reason",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="motif de la remise"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="inscrit"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="enrollments",
                        to="ecoles.classroom",
                        verbose_name="classe",
                    ),
                ),
            ],
            options={
                "verbose_name": "inscription",
            },
        ),
        migrations.AddField(
            model_name="classroom",
            name="schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="classrooms",
                to="ecoles.feeschedule",
                verbose_name="barème",
            ),
        ),
        migrations.CreateModel(
            name="Installment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Ex. : Inscription, 1re tranche",
                        max_length=80,
                        verbose_name="libellé",
                    ),
                ),
                ("amount", models.PositiveIntegerField(verbose_name="montant")),
                ("due_date", models.DateField(verbose_name="date limite")),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installments",
                        to="ecoles.feeschedule",
                    ),
                ),
            ],
            options={
                "verbose_name": "échéance",
                "ordering": ["due_date", "id"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveIntegerField(verbose_name="montant")),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("especes", "Espèces"),
                            ("wave", "Wave"),
                            ("orange_money", "Orange Money"),
                            ("mtn_momo", "MTN MoMo"),
                            ("moov_money", "Moov Money"),
                            ("en_ligne", "Paiement en ligne"),
                            ("virement", "Virement / versement bancaire"),
                            ("cheque", "Chèque"),
                            ("autre", "Autre"),
                        ],
                        default="especes",
                        max_length=20,
                        verbose_name="mode de paiement",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="N° de transaction mobile money, n° de chèque…",
                        max_length=80,
                        verbose_name="référence",
                    ),
                ),
                (
                    "paid_on",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="date du paiement",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="observation"
                    ),
                ),
                (
                    "receipt_number",
                    models.PositiveIntegerField(
                        editable=False, verbose_name="n° de reçu"
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        default=ecoles.utils.new_token,
                        editable=False,
                        max_length=40,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cancelled_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "cancel_reason",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="motif d'annulation"
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="payments",
                        to="ecoles.enrollment",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="ecoles.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "paiement",
                "ordering": ["-paid_on", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Reminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("whatsapp", "WhatsApp"),
                            ("sms", "SMS"),
                            ("appel", "Appel"),
                        ],
                        default="whatsapp",
                        max_length=20,
                    ),
                ),
                (
                    "amount_due",
                    models.PositiveIntegerField(verbose_name="montant réclamé"),
                ),
                ("message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="ecoles.enrollment",
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="ecoles.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "relance",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OnlineTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        default=ecoles.utils.new_reference, max_length=40, unique=True
                    ),
                ),
                ("provider", models.CharField(max_length=20)),
                ("amount", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("accepte", "Accepté"),
                            ("refuse", "Refusé"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                ("provider_reference", models.CharField(blank=True, max_length=120)),
                ("last_response", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="ecoles.enrollment",
                    ),
                ),
                (
                    "payment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transaction",
                        to="ecoles.payment",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="ecoles.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "transaction en ligne",
                "verbose_name_plural": "transactions en ligne",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="feeschedule",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="ecoles.school",
            ),
        ),
        migrations.AddField(
            model_name="classroom",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classrooms",
                to="ecoles.school",
            ),
        ),
        migrations.CreateModel(
            name="SchoolYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Ex. : 2026-2027",
                        max_length=20,
                        verbose_name="année scolaire",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="rentrée")),
                ("end_date", models.DateField(verbose_name="fin d'année")),
                (
                    "is_current",
                    models.BooleanField(default=False, verbose_name="année en cours"),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="years",
                        to="ecoles.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "année scolaire",
                "verbose_name_plural": "années scolaires",
                "ordering": ["-start_date"],
            },
        ),
        migrations.AddField(
            model_name="feeschedule",
            name="year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="ecoles.schoolyear",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="ecoles.schoolyear",
            ),
        ),
        migrations.AddField(
            model_name="classroom",
            name="year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classrooms",
                to="ecoles.schoolyear",
            ),
        ),
        migrations.CreateModel(
            name="StaffMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("directeur", "Direction / fondateur"),
                            ("caissier", "Caisse / secrétariat"),
                        ],
                        default="caissier",
                        max_length=20,
                        verbose_name="rôle",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff",
                        to="ecoles.school",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "membre du personnel",
                "verbose_name_plural": "personnel",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matricule", models.CharField(blank=True, max_length=40)),
                ("last_name", models.CharField(max_length=80, verbose_name="nom")),
                (
                    "first_name",
                    models.CharField(max_length=120, verbose_name="prénoms"),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("F", "Fille"), ("M", "Garçon")],
                        max_length=1,
                        verbose_name="sexe",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="date de naissance"
                    ),
                ),
                (
                    "parent_name",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="parent / tuteur"
                    ),
                ),
                (
                    "parent_phone",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="téléphone du parent"
                    ),
                ),
                (
                    "parent_phone2",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="autre téléphone"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes internes")),
                (
                    "token",
                    models.CharField(
                        default=ecoles.utils.new_token,
                        editable=False,
                        max_length=40,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="ecoles.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "élève",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.AddField(
            model_name="enrollment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="ecoles.student",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                fields=("school", "receipt_number"), name="recu_unique_par_ecole"
            ),
        ),
        migrations.AddConstraint(
            model_name="schoolyear",
            constraint=models.UniqueConstraint(
                fields=("school", "name"), name="annee_unique_par_ecole"
            ),
        ),
        migrations.AddConstraint(
            model_name="classroom",
            constraint=models.UniqueConstraint(
                fields=("year", "name"), name="classe_unique_par_annee"
            ),
        ),
        migrations.AddConstraint(
            model_name="enrollment",
            constraint=models.UniqueConstraint(
                fields=("student", "year"), name="une_inscription_par_an"
            ),
        ),
    ]
